### PR TITLE
fix: enhanced command limit

### LINKED ISSUE #52: Enhanced command limit
## Bug Report

- [x] I have searched the [issues](https://github.com/tidb-community-bots/challenge-bot/issues) of this repository and believe that this is not a duplicate.

### Related link

None

### Steps to reproduce(Optional)

Reward on Issue.
Pick up on PR.

### What is expected?
No reaction.

### What is actually happening?
Bot commented.

### PR DESCRIPTION
**Pull request by Mini256**
resolves #52

### CODE REVIEW

File: src/commands/give-up/index.ts [hunk 1]
```diff
@@ -17,7 +17,12 @@ const giveUp = async (
   context: Context,
   challengeIssueService: ChallengeIssueService
 ) => {
-  const issueResponse = await context.github.issues.get(context.issue());
+  const issue = context.issue();
+  const issueResponse = await context.github.issues.get({
+    owner: issue.owner,
```
Comment (hi-rustin) [inline src/commands/give-up/index.ts:22]: I think it can be `...context.issue()`.

File: src/commands/pick-up/index.ts [hunk 2]
```diff
@@ -22,8 +22,12 @@ const pickUp = async (
 ) => {
   // Notice: because the context come form issue_comment.created event,
   // so we need to get this issue.
-  const issueResponse = await context.github.issues.get(context.issue());
   const issue = context.issue();
+  const issueResponse = await context.github.issues.get({
+    owner: issue.owner,
```
Comment (hi-rustin) [inline src/commands/pick-up/index.ts:27]: ditto

File: src/commands/reward/index.ts [hunk 3]
```diff
@@ -33,15 +33,48 @@ const reward = async (
...
+          body: combineReplay({
+            data: null,
+            status: Status.Problematic,
+            message: ChallengePullMessage.NotValidPullRequest,
+            tip: ChallengePullTips.CanNotRewardIssue,
+          }),
+        })
+      );
+    } else {
+      console.error(e);
```
Comment (hi-rustin) [inline src/commands/reward/index.ts:63]: Please use context logger.

File: src/services/challenge-issue/index.ts [hunk 4]
```diff
@@ -168,6 +168,15 @@ export default class ChallengeIssueService {
       status: Status.Failed,
     };
 
+    // Check if is a pull request
+    if (pickUpQuery.issue?.isPullRequest) {
+      return {
```
Comment (hi-rustin) [inline src/services/challenge-issue/index.ts:173]: I think we should just ignore this command and no reply.

**Review by hi-rustin — CHANGES_REQUESTED** [review]

File: src/services/challenge-issue/index.ts (hunk 4 above)
Comment (Mini256) [reply src/services/challenge-issue/index.ts:173]: Should we log for it?

File: src/commands/reward/index.ts (hunk 3 above)
Comment (Mini256) [reply src/commands/reward/index.ts:63]: Good advice！

File: src/commands/give-up/index.ts (hunk 1 above)
Comment (Mini256) [reply src/commands/give-up/index.ts:22]: Good suggest

File: src/services/challenge-issue/index.ts (hunk 4 above)
Comment (hi-rustin) [reply src/services/challenge-issue/index.ts:173]: Yes, you can add some logs here.

File: src/commands/give-up/index.ts (hunk 1 above)
Comment (Mini256) [reply src/commands/give-up/index.ts:22]: I try to write in your way, but when I use the `...` operator, it will pass the `number` to the parameter, that will trigger the deprecation tips appears. I write this mainly to disappear it.

**Comment by Mini256** [comment]
PTAL~ @hi-rustin

**Comment by hi-rustin** [comment]
> PTAL~ @hi-rustin

I will review it tonight or tomorrow.

**Comment by Mini256** [comment]
> I will review it tonight or tomorrow.

ok, thanks!

**Comment by hi-rustin** [comment]
/hold 

Waiting refactor tests.

File: src/commands/pick-up/index.ts [hunk 5]
```diff
@@ -22,10 +23,22 @@ const pickUp = async (
...
+  });
   const { data } = issueResponse;
   const { sender } = context.payload;
+
+  // Check if an issue, if it is a pull request, no response.
+  if (data.pull_request != null) {
+    context.log.warn(ChallengeIssueWarning.NotAllowedToPickUpAPullRequest);
+    return;
+  }
+  console.log(2333);
```
Comment (hi-rustin) [inline src/commands/pick-up/index.ts:40]: Please remove it.

File: test/index.test.ts [hunk 6]
```diff
@@ -58,6 +64,40 @@ describe("My Probot app", () => {
...
+        user: {
+          login: "Rustin-Liu",
+          id: 1,
+        },
+        pull_request: {},
+      })
+      .get(
+        "/repos/Rustin-Liu/ti-challenge-bot/contents/.github/challenge-bot.yml",
+        (body) => {
+          // If the robot regards a pull request as an issue mistakenly, it will request this API, so that the body must not be undefined
```
Comment (hi-rustin) [inline test/index.test.ts:87]: Better add a period.

File: test/index.test.ts [hunk 7]
```diff
@@ -58,6 +64,40 @@ describe("My Probot app", () => {
...
+          expect(body).toBeUndefined();
+          done();
+          return true;
+        }
+      )
+      .reply(200);
+
+    // Receive a webhook event
```
Comment (hi-rustin) [inline test/index.test.ts:95]: ditto

File: test/index.test.ts [hunk 8]
```diff
@@ -2,17 +2,23 @@
...
 import payload from "./fixtures/issues.ping.comment.json";
-import typeorm = require("typeorm");
+import pickUpPayload from "./fixtures/pulls.pickup.comment.json";
+
 const pongBody = { body: "pong! I am challenge bot." };
 const fs = require("fs");
 const path = require("path");
 
+// Mock the challenge-issue service
+jest.mock("../src/services/challenge-issue/index");
```
Comment (hi-rustin) [inline test/index.test.ts:20]: Abstract the service as an interface and try to mock dependency injection.

File: src/commands/give-up/index.ts [hunk 9]
```diff
@@ -17,7 +17,12 @@ const giveUp = async (
...
+    repo: issue.repo,
+    issue_number: issue.number,
+  });
```
Comment (hi-rustin) [inline src/commands/give-up/index.ts:25]: It seems you are not checking here?

File: test/index.test.ts [hunk 10]
```diff
@@ -58,6 +64,40 @@ describe("My Probot app", () => {
...
+          id: 1,
+        },
+        pull_request: {},
+      })
+      .get(
+        "/repos/Rustin-Liu/ti-challenge-bot/contents/.github/challenge-bot.yml",
+        (body) => {
+          // If the robot regards a pull request as an issue mistakenly, it will request this API, so that the body must not be undefined
+          expect(body).toBeUndefined();
+          done();
```
Comment (hi-rustin) [inline test/index.test.ts:89]: Can we remove this done()?

**Review by hi-rustin — CHANGES_REQUESTED** [review]

File: src/commands/pick-up/index.ts (hunk 5 above)
Comment (Mini256) [reply src/commands/pick-up/index.ts:40]: Good catch！

File: test/index.test.ts (hunk 8 above)
Comment (Mini256) [reply test/index.test.ts:20]: But now the implementation is based on the target class injection. If we use `probot.receive` API to mock receving the `pick-up` command, It seems we can't change the input parameters of pickUp method. Should we change the way of injection?

```
commands(app, "pick-up", async (context: Context) => {
    await pickUp(context, Container.get(ChallengeIssueService));
});
```

Comment (hi-rustin) [reply test/index.test.ts:20]: I think you can mock the `Container.get`.

File: src/commands/give-up/index.ts [hunk 11]
```diff
@@ -32,7 +45,8 @@ const giveUp = async (
   };
 
   const reply = await challengeIssueService.giveUp(giveUpQuery);
-  if (reply === undefined) {
+
+  if (reply === undefined || reply === null) {
```
Comment (hi-rustin) [inline src/commands/give-up/index.ts:49]: I don't think reply can be null.

File: test/index.test.ts [hunk 12]
```diff
@@ -1,18 +1,40 @@
...
 const pongBody = { body: "pong! I am challenge bot." };
 const fs = require("fs");
 const path = require("path");
 
+// Mock the challenge-issue service
+const mockGiveUpMethod = jest.fn();
+const mockPickUpMethod = jest.fn();
+
+@Service(IChallengeIssueServiceToken)
+// @ts-ignore
```
[the remark this answers is not in the document]
Comment (Mini256) [reply test/index.test.ts:27]: Because that will show the experimentalDecorators tip without it.

[the remark this answers is not in the document]
Comment (hi-rustin) [reply test/index.test.ts:27]: Try to open this flag in `tsconfig.json`.

[the remark this answers is not in the document]
Comment (Mini256) [reply test/index.test.ts:27]: Actually, the option is already opened in the config file, but not work.

File: test/index.test.ts [hunk 13]
```diff
@@ -1,18 +1,40 @@
...
-import typeorm = require("typeorm");
+import pickUpPayload from "./fixtures/pulls.pickup.comment.json";
+import giveUpPayload from "./fixtures/pulls.giveup.comment.json";
+
 const pongBody = { body: "pong! I am challenge bot." };
 const fs = require("fs");
 const path = require("path");
 
+// Mock the challenge-issue service
+const mockGiveUpMethod = jest.fn();
```
Comment (hi-rustin) [inline test/index.test.ts:23]: I think we can move these code into before all.

File: test/index.test.ts [hunk 14]
```diff
@@ -58,6 +80,86 @@ describe("My Probot app", () => {
...
+        sha: "3d21ec53a331a6f037a91c368710b99387d012c1",
+        url:
+          "https://api.github.com/repos/Rustin-Liu/ti-challenge-bot/contents/.github/challenge-bot.yml",
+      });
+
+    // Receive a webhook event.
+    await probot.receive({ name: "issue_comment", payload: giveUpPayload });
+
+    // If the robot receive a give-up command to a pull request, the `giveUp` method will not be called.
+    expect(mockGiveUpMethod.mock.calls[0]).toBeUndefined();
```
Comment (hi-rustin) [inline test/index.test.ts:160]: It can be `expect(mockGiveUpMethod).not.toHaveBeenCalled()`.

**Review by hi-rustin — CHANGES_REQUESTED** [review]

File: test/index.test.ts (hunk 14 above)
Comment (Mini256) [reply test/index.test.ts:160]: Good idea!

**Review by hi-rustin — APPROVED** [review]
Good job! Thanks!

**Comment by Mini256** [comment]
> Good job! Thanks!

Thank your for your reviewing!
